// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgdoeeqfmztaxreamkkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZG9lZXFmbXp0YXhyZWFta2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODI3NjAsImV4cCI6MjA3NDM1ODc2MH0.Pvq-WIl1Mqo9IqguijC_QwLWG09QjZ6GbdqJwSVike4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});